version: "2.9"

services:
    web1:
        build: .
        container_name: web1
        depends_on:
            - redis
        ports:
            - "8081:8080"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SERVER_PORT=8080

    web2:
        build: .
        container_name: web2
        depends_on:
            - redis
        ports:
            - "8082:8080"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SERVER_PORT=8080

    web3:
        build: .
        container_name: web3
        depends_on:
            - redis
        ports:
            - "8083:8080"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - SERVER_PORT=8080

    redis:
        image: redis
        ports:
            - "6378:6379"
        volumes:
            - ./redis-volume:/data

    haproxy:
        image: haproxy
        container_name: haproxy
        depends_on:
            - web1
            - web2
            - web3
        ports:
            - "8080:8080"
            - "8404:8404"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
